// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilePickerController from "./file_picker_controller.js"
application.register("file-picker", FilePickerController)

import SortController from "./sort_controller.js"
application.register("sort", SortController)
